apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: rc-dev-kvs
  name: rc-dev-kvs
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: dev-kvs
    spec:
      containers:
      - name: dev-kvs
        resources:
          requests:
            cpu: 100m
          limits:
            memory: 1024Mi
        # redisのimageは最新版を使用すること。
        # GCRを見て確認。
      image: redis:3
        ports:
        - containerPort: 6379
