apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: rc-dev-app-1
  name: rc-dev-app-1
spec:
  replicas: 1
  selector:
    name: dev-app
    version: "20161130"
  template:
    metadata:
      labels:
        name: dev-app
        version: "20161130"
    spec:
      containers:
        - name: dev-app
          # 使用するアプリのイメージパスを指定
          image: php:7-apache
          imagePullPolicy: Always
          command: ["/usr/sbin/apachectl", "-D", "FOREGROUND" ]
          ports:
            - containerPort: 80
          volumeMounts:
            - name: app
              # mount先のディレクトリを指定
              mountPath: /app/
              readOnly: false
              # apacheのconfを書き換えるのであれば追加する。
            - name: httpd-conf
              mountPath: /etc/httpd/conf.d/zzz_zzz.conf
              readOnly: false
      volumes:
        - name: app
          # mount元のディレクトリを指定
          hostPath:
              path: /Users/k_ohhara/Workspace/docker
          # apacheのconfを実行時に書き換えるのであれば追加する
        - name: httpd-conf
          hostPath:
              path: /Users/k_ohhara/Workspace/docker/yaml/zzz_zzz.conf
