apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: rc-phpmyadmin-1
  name: rc-phpmyadmin-1
spec:
  replicas: 1
  selector:
    name: phpmyadmin
    version: "20161130"
  template:
    metadata:
      labels:
        name: phpmyadmin
        version: "20161130"
    spec:
      containers:
        - name: phpmyadmin
          # phpmyadminの公式イメージを使用する
          image: phpmyadmin/phpmyadmin
          ports:
            - containerPort: 80
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: ""
            - name: MYSQL_USER
              value: "root"
            - name: MYSQL_PASSWORD
              value: ""
            - name: PMA_HOST
              value: "svc-mysql"

